# Culculate Bonuses

In [63]:
import pandas as pd

In [1]:
# Not in qualtrics data but with choices
need_to_add = ['674377f77b539c33d343553c',
               '63c5514d060f9b8e66cab38f',
               '6609a35ed745fef53c0c1034',
               ]

In [65]:
qualtrics_csv = "raw_data/qualtrics2_values.csv"
prolific_csv = "raw_data/prolific2_real.csv"
qualtrics_df = pd.read_csv(qualtrics_csv)

exp_start_time = pd.to_datetime("2026-03-25 00:00:00")
exp_end_time = pd.to_datetime("2026-03-31 23:00:00")


qualtrics_ids = qualtrics_df['ProlificID'].tolist()
qualtrics_df['StartDate'] = pd.to_datetime(qualtrics_df['StartDate'], errors='coerce')
qualtrics_df['EndDate'] = pd.to_datetime(qualtrics_df['EndDate'], errors='coerce')
# Filter the data
rellevant_qualtrics = qualtrics_df[
    (qualtrics_df['StartDate'] >= exp_start_time) & (qualtrics_df['StartDate'] <= exp_end_time) &
    (qualtrics_df['ProlificID'].astype(str).str.len() > 20) &
    ((qualtrics_df['Finished'] == 'True') | (qualtrics_df['Finished'] == '1'))  # Ensure the survey was completed
]
display(rellevant_qualtrics.tail(3))

C:\Users\matan\AppData\Local\Temp\ipykernel_97000\2968655044.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  qualtrics_df['StartDate'] = pd.to_datetime(qualtrics_df['StartDate'], errors='coerce')
C:\Users\matan\AppData\Local\Temp\ipykernel_97000\2968655044.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  qualtrics_df['EndDate'] = pd.to_datetime(qualtrics_df['EndDate'], errors='coerce')

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,AI_4,AI_5,comments,Q261,Random_ID,AWSURL,group,ProlificID,agent_level,bonus_group
432,2026-03-31 11:32:17,2026-03-31 12:09:06,0,113.20.53.80,100,2208,1,2026-03-31 12:09:07,R_6Q2PXQg3t2j6F5T,NaN,...,4,5,NaN,NaN,9962396258,NaN,1,67ef5e1ea8330a7744f39e17,NaN,2321
435,2026-03-31 12:09:59,2026-03-31 12:31:53,0,207.216.102.94,100,1313,1,2026-03-31 12:31:53,R_1uDGiWr0d8tlkjU,NaN,...,1,5,NaN,NaN,8809856549,NaN,1,67d09fef5654f3194dc6c5a6,NaN,NaN
439,2026-03-31 12:30:32,2026-03-31 12:42:49,0,73.153.55.215,100,737,1,2026-03-31 12:42:50,R_5e3jPAoFZqxgAV3,NaN,...,7,4,NaN,NaN,9354094976,NaN,3,69b33295dd6af6d1010798f4,NaN,2323

In [2]:
from mysql_data_explorer import get_all_tables_from_mysql, alter_database_tables
import pandas as pd

all_tabels = get_all_tables_from_mysql()
print(all_tabels.keys())

✅ Connected to Azure MySQL database: dpu_fruitbot
📊 Found 4 tables: ['feedback_actions', 'user_choices', 'user_tutorial', 'users']

c:\Users\matan\master_thesis\rl_envs\procgen\experiments\mysql_data_explorer.py:83: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, self.connection)

   ✅ Loaded 'feedback_actions': 27059 rows, 13 columns
   ✅ Loaded 'user_choices': 2582 rows, 17 columns
   ✅ Loaded 'user_tutorial': 847 rows, 7 columns
   ✅ Loaded 'users': 1324 rows, 5 columns
🔌 Database connection closed
dict_keys(['feedback_actions', 'user_choices', 'user_tutorial', 'users'])

In [ ]:
import numpy as np

user_choices_results = all_tabels['user_choices']

user_id = "674377f77b539c33d343553c"
display(user_choices_results[user_choices_results['user_id'] == user_id])

,id,user_id,old_agent_name,new_agent_name,timestamp,demonstration_time,episode_index,choice_to_update,choice_explanation,similarity_level,feedback_score,feedback_count,env_level_feedback,env_level_demonstration,env_config_demonstration,agent_rating,feedback_correctness
1952,1973,674377f77b539c33d343553c,1,2,2026-03-31 11:51:34,2026-03-31 11:51:11,2,0,,4,0.0,2,94,50,2,4.0,2.0
1970,1991,674377f77b539c33d343553c,1,5,2026-03-31 11:54:19,2026-03-31 11:54:00,3,0,,4,0.0,2,91,45,3,5.0,1.0
1976,1997,674377f77b539c33d343553c,1,5,2026-03-31 11:55:34,2026-03-31 11:55:16,4,0,,4,0.0,1,59,94,1,4.0,0.0
1993,2014,674377f77b539c33d343553c,1,4,2026-03-31 11:57:07,2026-03-31 11:56:52,5,1,,4,0.0,2,78,63,3,6.0,0.0
2185,2206,63c5514d060f9b8e66cab38f,1,4,2026-03-31 15:47:20,2026-03-31 15:46:46,1,1,,4,0.0,30,96,4,2,4.0,11.0
2258,2279,63c5514d060f9b8e66cab38f,4,1,2026-03-31 15:55:30,2026-03-31 15:55:10,2,1,,4,0.0,103,50,74,3,2.0,55.0
2299,2320,63c5514d060f9b8e66cab38f,1,4,2026-03-31 15:59:30,2026-03-31 15:58:55,3,0,,4,0.0,53,61,22,3,6.0,18.0
2315,2336,63c5514d060f9b8e66cab38f,1,2,2026-03-31 16:03:00,2026-03-31 16:02:46,4,1,,4,0.0,47,26,27,1,4.0,12.0
2336,2357,63c5514d060f9b8e66cab38f,2,4,2026-03-31 16:08:11,2026-03-31 16:07:44,5,0,,4,0.0,55,53,62,3,4.0,16.0
2343,2364,6609a35ed745fef53c0c1034,1,3,2026-03-31 16:12:42,2026-03-31 16:09:13,1,1,,1,0.0,1,79,79,2,3.0,1.0
2350,2371,6609a35ed745fef53c0c1034,3,6,2026-03-31 16:20:20,2026-03-31 16:18:27,5,1,,1,0.0,3,82,82,3,5.0,0.0

In [68]:
# prolific_csv = "raw_data/prolific_real1.csv"
prolific_df = pd.read_csv(prolific_csv)
prolific_df = prolific_df[prolific_df['Status'] == "AWAITING REVIEW"]
prolific_ids = prolific_df['Participant id'].tolist()
feedback_actions = all_tabels['feedback_actions']
feedback_user_ids = feedback_actions['user_id'].tolist()
actives_users = []
non_actives_users = []
for prolific_id in prolific_ids:
    # First check if user has bonus_group in rellevant_qualtrics
    user_qualtrics = rellevant_qualtrics[rellevant_qualtrics['ProlificID'] == prolific_id]
    if user_qualtrics.empty  or user_qualtrics['Finished'].iloc[0] == 'False': # or user_qualtrics['bonus_group'].isna().all()
        non_actives_users.append(prolific_id)
        continue

    if prolific_id not in feedback_user_ids:
        non_actives_users.append(prolific_id)
        continue
    
    actives_users.append(prolific_id)
save_path = "prolific_approves/approved_users.csv"
pd.DataFrame(actives_users, columns=['ProlificID']).to_csv(save_path, index=False)
print(f"Active users count: {len(actives_users)}")
print(f"non active users: {non_actives_users}")


# calculate the bonuses
# correct_answers = answer_dict
filtered_df_no_null = rellevant_qualtrics[rellevant_qualtrics['ProlificID'].isin(actives_users)]
bonus_fields = ["ProlificID", "Bonus"]

bonus_map = {"APPL1": 0, "APPL2": 0, "APPL3": 0.5, "APPL4": 0.5, "APPL5": 0.7, "APPL6": 1, 
             "2321": 0, "2322": 0.5, "2323": 1}
# filtered_df_no_null["Bonus"] = filtered_df_no_null["bonus_group"].map(bonus_map).fillna(0)
filtered_df_no_null["Bonus"] = filtered_df_no_null["Q171"].map(bonus_map).fillna(0)
"""bonus"""
bonus_df = filtered_df_no_null[filtered_df_no_null["Bonus"] != 0]
# df = get_bonus(df, bonus, correct_answers)
bonus_df = filtered_df_no_null[bonus_fields]
bonus_df = bonus_df[bonus_df["Bonus"] > 0]
bonus_df.to_csv("prolific_approves/bonus.csv", index=False)

Active users count: 85
non active users: ['5d4043f25458cb0001d164a0', '63c5514d060f9b8e66cab38f', '6609a35ed745fef53c0c1034', '67d8a842726644308266e91f', '69aae13a0fb8430d9b481abf', '67e268cbf13dcd115337894c', '6997a232168a53f1d28191e1', '69a7e18d4c24cacdbb47110c', '58d7ab1b31506e0001447859', '5ee4c4b42c280d1cd26cfe3d', '5f2aec6a4e6d4d428ab5bd8e', '699dd4a7489b89db7ae91f17', '699ece8a778dfb99b080dfba']

C:\Users\matan\AppData\Local\Temp\ipykernel_97000\2140741733.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df_no_null["Bonus"] = filtered_df_no_null["Q171"].map(bonus_map).fillna(0)

# User preformance in the DataBase

In [69]:
from mysql_data_explorer import get_all_tables_from_mysql, alter_database_tables
import pandas as pd

all_tabels = get_all_tables_from_mysql()
print(all_tabels.keys())

✅ Connected to Azure MySQL database: dpu_fruitbot
📊 Found 4 tables: ['feedback_actions', 'user_choices', 'user_tutorial', 'users']

c:\Users\matan\master_thesis\rl_envs\procgen\experiments\mysql_data_explorer.py:83: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, self.connection)

   ✅ Loaded 'feedback_actions': 26929 rows, 13 columns
   ✅ Loaded 'user_choices': 2570 rows, 17 columns
   ✅ Loaded 'user_tutorial': 844 rows, 7 columns
   ✅ Loaded 'users': 1284 rows, 5 columns
🔌 Database connection closed
dict_keys(['feedback_actions', 'user_choices', 'user_tutorial', 'users'])

In [70]:
user_choices_results = all_tabels['user_choices']
user_choices_results.tail(2)

,id,user_id,old_agent_name,new_agent_name,timestamp,demonstration_time,episode_index,choice_to_update,choice_explanation,similarity_level,feedback_score,feedback_count,env_level_feedback,env_level_demonstration,env_config_demonstration,agent_rating,feedback_correctness
2568,2587,69137b85e53000767655dedc,2,3,2026-03-31 18:49:38,2026-03-31 18:48:54,3,1,,4,0.0,81,72,33,2,7.0,28.0
2569,2588,69137b85e53000767655dedc,3,4,2026-03-31 18:52:56,2026-03-31 18:52:11,5,0,,4,0.0,20,12,78,2,4.0,8.0

In [71]:
import numpy as np

user_choices_results = all_tabels['user_choices']

user_id = "69aae13a0fb8430d9b481abf"
display(user_choices_results[user_choices_results['user_id'] == user_id])

Empty DataFrame
Columns: [id, user_id, old_agent_name, new_agent_name, timestamp, demonstration_time, episode_index, choice_to_update, choice_explanation, similarity_level, feedback_score, feedback_count, env_level_feedback, env_level_demonstration, env_config_demonstration, agent_rating, feedback_correctness]
Index: []

In [72]:
user_feedbacks = all_tabels['feedback_actions']
display(user_feedbacks[user_feedbacks['user_id'] == user_id])

Empty DataFrame
Columns: [id, user_id, env_state, agent_action, feedback_action, feedback_explanation, action_index, timestamp, episode_index, agent_name, similarity_level, env_level, env_config]
Index: []